---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go mod download
    - go test ./...
    - export DOCKER_PASSWORD=$(aws ecr get-login-password --region us-east-1)
    - export DOCKER_USERNAME=AWS
builds:
  -
    binary: go-releaser-test
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags -static
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Timestamp}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - 620354051118.dkr.ecr.us-east-1.amazonaws.com/toast/{{.ProjectName}}:{{ .Tag }}
      - 620354051118.dkr.ecr.us-east-1.amazonaws.com/toast/{{.ProjectName}}:latest
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{incpatch .Version}}-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
